# Generated by Django 3.0.8 on 2020-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0002_excuse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondocumentation',
            name='group_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Group note'),
        ),
    ]
