# Generated by Django 3.1.6 on 2021-02-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0010_events_extra_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnote',
            name='late',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
